#!/bin/sh
# A wrapper around the runner which automatically removes it when it finishes

: ${GITHUB_REPO?Must provide GITHUB_REPO env variable.}
: ${GITHUB_REPO_TOKEN?Must provide GITHUB_REPO_TOKEN env variable.}

set -eo pipefail

GITHUB_RUNNER_TOKEN=$(\
    curl \
        -X POST \
        -H "Authorization: token $GITHUB_REPO_TOKEN" \
        "https://api.github.com/repos/${GITHUB_REPO}/actions/runners/registration-token" \
    | jq -r '.token' \
)

exit_code=0
(
    set -e;
    ${APP_ROOT}/src/config.sh \
        --replace \
        --token ${GITHUB_RUNNER_TOKEN} \
        --unattended \
        --url https://github.com/${GITHUB_REPO}/

    ${APP_ROOT}/src/run.sh
) || {
    exit_code="$?"
}

# remove the configured runner
${APP_ROOT}/src/config.sh remove \
    --token ${GITHUB_RUNNER_TOKEN} \
    --unattended \
    --url https://github.com/${GITHUB_REPO}/

exit $exit_code
